version: 1

formatters:
  simple:
    format: '%(asctime)s %(threadName)s %(levelname)7s %(name)10s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ${PROJ_HOME}/log/train/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ${PROJ_HOME}/log/train/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  main:
    level: DEBUG
    propagate: no

root:
  level: DEBUG
  handlers: [console, debug_file_handler, error_file_handler]
  propagate: yes