emb-size: 50 # 100 - Glove
hidden-size: 50 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.bin
model-file: data/train/model.ckpt

train:
  lr: 0.01
  lr-decay-epoch: 25
  clip-gradient-max-norm: 1
  forcing-ratio: 0.90
  forcing-decay: 0.05
  rl-transit-epoch: -1
  rl-transit-decay: 0
  rl-weight: 0.7
  epoch: 75
  batch-size: 20
  log-batch: false
  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/train/vocab.bin
  emb-file: data/extract/embedding
  model-file: data/train/model.ckpt