emb-size: 100
emb-file: data/train/embedding

enc-hidden-size: 100
dec-hidden-size: 200

max-enc-steps: 100
max-dec-steps: 100

vocab-size: 50000
vocab-file: data/train/vocab.txt

model-file: data/train/model.ckpt

pointer-generator: true
share-dec-weight: true

device: cpu

train:
  epoch: 50
  batch-size: 5
  log-batch: true
  log-batch-interval: 1
  clip-gradient-max-norm:

  lr: 0.001
  lr-decay: 1
  lr-decay-epoch: 50

  ml:
    enable: false
    forcing-ratio: 0.7
    forcing-decay: 0
  rl:
    enable: true
    transit-epoch: 1
    transit-decay: 0
    weight: 0.9984

  eval: true

  tb-log-dir: logs/giga/

  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  keyword-file: data/train/keyword.txt

  load-model-file:
  save-model-file: data/result/model.ckpt
  save-model-per-epoch:

eval:
  batch-size: 20
  log-batch: true
  log-batch-interval: 2

  load-model-file: data/result/model.ckpt

  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  keyword-file: data/train/keyword.txt