emb-size: 5 # 100 - Glove
hidden-size: 5 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-size: 10000
vocab-file: data/extract/vocab.txt

model-file: data/extract/model.ckpt

sharing-decoder-weight: true

train:
  epoch: 5
  batch-size: 20
  log-batch: true
  log-batch-interval: 1
  clip-gradient-max-norm: 1

  lr: 0.001
  lr-decay: 1
  lr-decay-epoch: 50

  ml:
    enable: true
    forcing-ratio: 1
    forcing-decay: 0
  rl:
    enable: false
    transit-epoch: -1
    transit-decay: 0
    weight: 0.9984

  eval: true

  tb-log-dir: logs/giga-5k/

  article-file: data/extract/article.txt
  summary-file: data/extract/summary.txt
  keyword-file: data/extract/keyword.txt
  vocab-file: data/extract/vocab.txt
  emb-file: data/extract/embedding
  model-file:
  save-model-file: data/extract/model.ckpt