emb-size: 50 # 100 - Glove
hidden-size: 50 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.bin
model-file: data/train/model.ckpt

train:
  epoch: 75
  batch-size: 20
  log-batch: false
  clip-gradient-max-norm: 1

  lr: 0.01
  lr-decay: 0.9
  lr-decay-epoch: 25

  ml:
    enable: true
    forcing-ratio: 0.90
    forcing-decay: 0.05
  rl:
    enable: false
    transit-epoch: -1
    transit-decay: 0
    weight: 0.9984

  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/train/vocab.bin
  emb-file: data/extract/embedding
  save-model-file: data/train/model.ckpt