emb-size: 50 # 100 - Glove
hidden-size: 100 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.txt
model-file: data/train/model.ckpt

train:
  learning_rate: 0.0001
  clip_gradient_max_norm: 0.25
  forcing_ratio: 1
  forcing_decay: 0.05
  rl_transit_epoch: -1
  rl_transit_decay: 0
  rl-weight: 0.7
  epoch: 100
  batch-size: 30
  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/extract/vocab.bin
  #vocab-file: data/train/vocab.txt
  emb-file: data/extract/embedding.dat    # only Glove
  model-file: data/train/model.ckpt