emb-size: 50 # 100 - Glove
hidden-size: 50 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.txt
model-file: data/train/model.ckpt

train:
  forcing_ratio: 0.7
  forcing_decay: 0.05
  learning_rate: 0.001
  rl_transit_decay: 0.05
  rl-weight: 0.7
  epoch: 100
  batch-size: 10
  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/train/vocab.txt
  model-file: data/train/model.ckpt