emb-size: 50
emb-file:

enc-hidden-size: 50
dec-hidden-size: 100

max-enc-steps: 100
max-dec-steps: 50

vocab-size: 50000
vocab-file: data/train/vocab.txt

model-file: data/result/model.ckpt

pointer-generator: true
share-dec-weight: true

device: cpu

logging:
  enable: true
  conf-file:

train:
  epoch: 100
  batch-size: 1
  log-batch: true
  log-batch-interval: 1
  clip-gradient-max-norm: 1

  lr: 0.001
  lr-decay: 1
  lr-decay-epoch: 50

  ml:
    enable: true
    forcing-ratio: 0.75
    forcing-decay: 0
  rl:
    enable: false
    transit-epoch: -1
    transit-decay: 0
    weight: 0.9984

  eval: true

  tb:
    enable: true
    log-batch: true
    log-dir: ${PROJ_HOME}/log/tb/

  article-file: data/train/training.article.txt
  summary-file: data/train/training.summary.txt
  keyword-file: data/train/training.keyword.txt

  load-model-file:
  save-model-file: data/result/model.ckpt
  save-model-per-epoch: 1

eval:
  batch-size: 3
  log-batch: true
  log-batch-interval: 1

  load-model-file: data/result/model.ckpt

  article-file: data/train/training.article.txt
  summary-file: data/train/training.summary.txt
  keyword-file: data/train/training.keyword.txt