emb-size: 5 # 100 - Glove
hidden-size: 5 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.txt
model-file: data/train/model.ckpt

train:
  forcing_ratio: 0.90
  forcing_decay: 0.9999
  learning_rate: 0.0001
  rl-weight: 0.9984
  epoch: 1
  batch-size: 10
  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/train/vocab.txt
  model-file: data/train/model.ckpt