emb-size: 5 # 100
emb-file: data/extract/embedding

enc-hidden-size: 5 # 200
dec-hidden-size: 10 # 400

max-enc-steps: 100
max-dec-steps: 100

vocab-size: 5000
vocab-file: data/extract/giga-vocab.txt

model-file: data/extract/giga-model.ckpt

pointer-generator: false
share-dec-weight: false

device: cpu

train:
  epoch: 1
  batch-size: 2
  log-batch: true
  log-batch-interval: 1
  clip-gradient-max-norm: 1

  lr: 0.001
  lr-decay: 1
  lr-decay-epoch: 50

  ml:
    enable: false
    forcing-ratio: 1
    forcing-decay: 0
  rl:
    enable: true
    transit-epoch: 1
    transit-decay: 0
    weight: 0.9984

  eval: true

  tb-log-dir: logs/giga/

  article-file: data/extract/giga-article.txt
  summary-file: data/extract/giga-summary.txt
  keyword-file: data/extract/giga-keyword.txt

  load-model-file:
  save-model-file: data/result/giga-model.ckpt
  save-model-per-epoch:

eval:
  batch-size: 20
  log-batch: true
  log-batch-interval: 2

  load-model-file: data/result/giga-model.ckpt

  article-file: data/extract/giga-article.txt
  summary-file: data/extract/giga-summary.txt
  keyword-file: data/extract/giga-keyword.txt