emb-size: 50 # 100 - Glove
hidden-size: 50 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-size: 50000
vocab-file: data/extract/giga-vocab.txt

model-file: data/extract/giga-model.ckpt

train:
  epoch: 100
  batch-size: 20
  log-batch: true
  clip-gradient-max-norm: 1

  lr: 0.0001
  lr-decay: 0.1
  lr-decay-epoch: 40

  ml:
    enable: true
    forcing-ratio: 1
    forcing-decay: 0
  rl:
    enable: false
    transit-epoch: -1
    transit-decay: 0
    weight: 0.9984

  article-file: data/extract/giga-article.txt
  #article-file: data/extract/train.article.txt
  summary-file: data/extract/giga-summary.txt
  #summary-file: data/extract/train.title.txt
  vocab-file: data/extract/giga-vocab.txt
  emb-file: data/extract/embedding
  save-model-file: data/extract/giga-model.ckpt