emb-size: 50 # 100 - Glove
hidden-size: 50 # 200

max-enc-steps: 100
max-dec-steps: 100

vocab-file: data/train/vocab.bin
model-file: data/train/model.ckpt

train:
  learning_rate: 0.0001
  clip_gradient_max_norm: 1
  forcing_ratio: 1
  forcing_decay: 0.05
  rl_transit_epoch: -1
  rl_transit_decay: 0
  rl-weight: 0.7
  epoch: 200
  batch-size: 20
  log_batch: false
  article-file: data/train/article.txt
  summary-file: data/train/summary.txt
  vocab-file: data/train/vocab.bin
  emb-file: data/extract/embedding
  model-file: data/train/model.ckpt