emb-size: 100
emb-file:

enc-hidden-size: 100
dec-hidden-size: 200

max-enc-steps: 800
max-dec-steps: 100

vocab-size: 50000
vocab-file: data/extract/vocab.txt

intra-dec-attn: true
pointer-generator: true
share-dec-weight: true

device: cpu

logging:
  enable: true
  conf-file:

eval:
  batch-size: 30
  log-batch: true
  log-batch-interval: 1

  load-model-file: data/result/model.ckpt

  article-file: data/validation/validation.article.txt
  summary-file: data/validation/validation.summary.txt
  keyword-file: data/validation/validation.keyword.txt